FROM local/c7-systemd

MAINTAINER drdukes@gmail.com

COPY samba.service /etc/systemd/system/samba.service

RUN yum clean all && yum install -y \
	iproute \
	less \
	openssh-server \
	rsyslog \
	wget;
	
RUN wget -O - "http://10.0.1.7:9080/samba-4.6.5.tar.gz" > /tmp/samba-4.6.5.tar.gz && \
	cd /tmp && \
	tar zxf samba-4.6.5.tar.gz -C /usr/local && \
	chmod 755 /usr/local/samba; \
	rm -f /tmp/samba-4.6.5.tar.gz && \
	[ -e "/etc/ssh/sshd_config" ] && \
	sed -i 's/PermitRootLogin without-password/PermitRootLogin yes/' /etc/ssh/sshd_config; \
	sed -i 's/#UseDNS yes/UseDNS no/' /etc/ssh/sshd_config ;\
	echo "root:password" | chpasswd; \
	systemctl enable samba.service;

CMD ["/usr/sbin/init", "/bin/bash"]
